name: Stage - Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [stage]
  pull_request:
    branches: [stage]

jobs:
  sftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: 🔨 Build Project
        run: |
          npm i    
          gulp build-prod

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: 217.21.92.35
          REMOTE_USER: u778408432
          REMOTE_PORT: '65002'
          TARGET: domains/codedthemes.com/public_html/demos/admin-templates/light-able/bootstrap/stage
          EXCLUDE: "/node_modules/"
